FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./

# Install build dependencies
RUN apk add --no-cache python3 make g++ \
    && npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "dev"]
